openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/bands/{id}:
    get:
      tags:
      - band-rest-controller
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BandDto'
    put:
      tags:
      - band-rest-controller
      operationId: updateBand
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BandDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BandDto'
    delete:
      tags:
      - band-rest-controller
      operationId: deleteBand
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BandDto'
  /api/bands:
    get:
      tags:
      - band-rest-controller
      operationId: findAll
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BandDto'
    post:
      tags:
      - band-rest-controller
      operationId: createBand
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BandDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BandDto'
  /api/bands/{idBand}/activities:
    get:
      tags:
      - band-activities-rest-controller
      operationId: findAll_1
      parameters:
      - name: idBand
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /api/bands/{idBand}/activities/{idActivity}:
    get:
      tags:
      - band-activities-rest-controller
      operationId: findById_1
      parameters:
      - name: idBand
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: idActivity
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
components:
  schemas:
    BandDto:
      required:
      - activitiesIds
      - albumsIds
      - image
      - managerId
      - membersIds
      - name
      - style
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        style:
          type: string
          enum:
          - ROCK
          - POP
          - PUNK
          - COUNTRY
          - RAP
          - K_POP
          - FUNK
          - REGGAE
          - FOLK
          - JAZZ
          - DISCO
          - CLASSIC
          - BLUES
          - VOCAL
        image:
          type: array
          items:
            type: string
            format: byte
        membersIds:
          type: array
          items:
            type: integer
            format: int64
        albumsIds:
          type: array
          items:
            type: integer
            format: int64
        activitiesIds:
          type: array
          items:
            type: integer
            format: int64
        managerId:
          type: integer
          format: int64
