openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/tours/{id}:
    get:
      tags:
      - tour-rest-controller
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TourDto'
    put:
      tags:
      - tour-rest-controller
      operationId: updateTour
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TourDto'
    delete:
      tags:
      - tour-rest-controller
      operationId: deleteTour
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TourDto'
  /api/tours:
    get:
      tags:
      - tour-rest-controller
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TourDto'
    post:
      tags:
      - tour-rest-controller
      operationId: createTour
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TourDto'
components:
  schemas:
    TourDateDto:
      required:
      - city
      - date
      - venue
      type: object
      properties:
        city:
          type: string
        date:
          type: string
          format: date
        venue:
          type: string
    TourDto:
      required:
      - bandList
      - name
      - tourDates
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        bandList:
          type: array
          items:
            type: integer
            format: int64
        tourDates:
          type: array
          items:
            $ref: '#/components/schemas/TourDateDto'
